### ISSUE TITLE
unable to delete branch: "Internal Error"

### ISSUE THREAD

**Issue by brainchild0** [yuki-kimoto/gitprep#169] opened 2020-05-28 03:54 UTC
The application is failing to delete a branch. 

(Note that in this case the name of the branch is `master`. It was created by the application to initialize the repository, but is not needed.)

The web interface prints a message "Internal Error", and the log shows the following:

```
[Wed May 27 20:47:33 2020] [error] /gitprep.cgi/user/repo/branches?op=delete: Branch deleting failed. Can't delete branch master at template /branches.html.ep line 40.
95:     # Icky backwards compatibility wrapper. :-(
96:     local @CARP_NOT = $cgc ? $cgc->() : caller();
97:     shortmess_heavy(@_);
98: }
99: 
100: sub croak   { die shortmess @_ }
101: sub confess { die longmess @_ }
102: sub carp    { warn shortmess @_ }
103: sub cluck   { warn longmess @_ }
104: 
105: BEGIN {
```

**Comment by yuki-kimoto** [comment] 2020-05-31 23:46
Do you want to delete master branch?

**Comment by brainchild0** [comment] 2020-06-01 00:10
Yes, in this case the application created a branch called `master` in  a new repository. I wanted to push a branch called `develop` from the client, because the project has no branch named `master`.  I then set `develop` to the default branch, but I cannot delete `master`.

**Comment by yuki-kimoto** [comment] 2020-06-01 07:05
Can you pull request?

or do you hope I fix it?

**Comment by brainchild0** [comment] 2020-06-01 07:12
I had no plans to make a PR, but maybe some day I could try.

**Comment by yuki-kimoto** [comment] 2020-06-01 08:42
Honestly, Currently I have busy to do other Open Source Perl Projects. I want to fix many bugs in GitPrep and want GitPrep become Completely Private Gihub-like sysmte containing Installation process. 

If you pull request, I can merge it!

**Comment by bilogic** [comment] 2021-06-15 09:42
> Honestly, Currently I have busy to do other Open Source Perl Projects. I want to fix many bugs in GitPrep and want GitPrep become Completely Private Gihub-like sysmte containing Installation process.
> 
> If you pull request, I can merge it!

Hmm... how about a PHP/Laravel port? There are many developers from that community who can help haha 😎

**Comment by yuki-kimoto** [comment] 2021-06-15 23:12
Sorry. PHP is Perl's competitor on the Web.

I'm working to popularize Perl and Mojolicious in Web develpoment.

PHP is an easy-to-use language.

However, I'm a Perl user and invest in Perl.

**Comment by bilogic** [comment] 2021-06-16 01:27
@yuki-kimoto 

Haha, your fighting spirit is commendable :)
Do you mind telling me where is the database structure for giitprep?

**Comment by yuki-kimoto** [comment] 2021-06-16 02:01
Gitpre Database is SQLite.

```
sqlite3 data/gitprep.db
```

**Comment by monnerat** [comment] 2024-08-29 20:28
Tried today with snapshot [9df7c7d](https://github.com/yuki-kimoto/gitprep/commit/9df7c7d763e14fb5d9735f4ec1c54afc8cbf93b7): can't reproduce problem. "master" branch deletion OK if default branch is something else.

**Comment by yuki-kimoto** [comment] 2024-08-29 23:06
I'll close this issue for now. If you encounter any further problems, please feel free to reopen it.

**Closed by yuki-kimoto** 2024-08-29 23:06 UTC
